security:
    encoders:
         FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
         chain_provider:
              chain:
                providers: [fos_userbundle]
         fos_userbundle:
                 id: fos_user.user_provider.username_email
#         fos_facebook_provider:
#                 id: fos_facebook.user.login
    firewalls:
        main:
            pattern:    ^/
            anonymous:      true
            provider:       main
#            fos_facebook:
#                  app_url: "//apps.facebook.com//justtrip"
#                  server_url: "www.justtrip.in"
#                  login_path: trip_site_management_homepage
#                  check_path: _security_check
#                  provider: fos_facebook_provider
#                  default_target_path: /
#                  success_handler: security.authentication.customized_success_handler
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                use_forward:    false
                use_referer : true
                provider: fos_userbundle
                success_handler: security.authentication.customized_success_handler
                failure_handler: security.authentication.customized_success_handler
            logout:
                path:   fos_user_security_logout
                target: room_booking_engine_homepage
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/.login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/(.+), roles: IS_AUTHENTICATED_FULLY }      
        #- { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
 
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: ROLE_USER }  
        #- { path: ^/(.+), roles: IS_AUTHENTICATED_FULLY }
        # no authentication for the homepage:
        #- { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
